export const Roles = {
  GENERAL_MANAGER: 'GENERAL_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  FINANCIAL_MANAGER: 'FINANCIAL_MANAGER',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  ASSISTANT_PROJECT_MANAGER: 'ASSISTANT_PROJECT_MANAGER',
  TEAM_LEAD: 'TEAM_LEAD',
  TECHNICAL_STAFF: 'TECHNICAL_STAFF',
};

export const TaskStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const GoalPeriod = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
};

export const Permission = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_USER_STATUS: 'MANAGE_USER_STATUS',
  RESET_USER_PASSWORDS: 'RESET_USER_PASSWORDS',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',
  APPROVE_PROJECTS: 'APPROVE_PROJECTS',
  MANAGE_TASKS: 'MANAGE_TASKS',
  APPROVE_TASKS: 'APPROVE_TASKS',
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',
  VIEW_EXECUTIVE_REPORTS: 'VIEW_EXECUTIVE_REPORTS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_GAMIFICATION: 'MANAGE_GAMIFICATION',
  MANAGE_MATERIAL_CATALOG: 'MANAGE_MATERIAL_CATALOG',
  MANAGE_MATERIAL_INVENTORY: 'MANAGE_MATERIAL_INVENTORY',
  CREATE_MATERIAL_REQUESTS: 'CREATE_MATERIAL_REQUESTS',
  REVIEW_MATERIAL_REQUESTS: 'REVIEW_MATERIAL_REQUESTS',
  PREPARE_MATERIAL_REQUESTS: 'PREPARE_MATERIAL_REQUESTS',
  DISPATCH_MATERIAL_REQUESTS: 'DISPATCH_MATERIAL_REQUESTS',
  RECONCILE_MATERIAL_CUSTODY: 'RECONCILE_MATERIAL_CUSTODY',
  CLOSE_MATERIAL_CUSTODY: 'CLOSE_MATERIAL_CUSTODY',
  VIEW_MATERIAL_REPORTS: 'VIEW_MATERIAL_REPORTS',
};

export const RolePermissions = {
  [Roles.GENERAL_MANAGER]: Object.values(Permission),
  [Roles.HR_MANAGER]: [
    Permission.MANAGE_USERS,
    Permission.MANAGE_USER_STATUS,
    Permission.RESET_USER_PASSWORDS,
    Permission.MANAGE_PERMISSIONS,
    Permission.VIEW_ANALYTICS,
    Permission.VIEW_EXECUTIVE_REPORTS,
  ],
  [Roles.FINANCIAL_MANAGER]: [
    Permission.APPROVE_PROJECTS,
    Permission.VIEW_FINANCIAL_REPORTS,
    Permission.VIEW_ANALYTICS,
    Permission.VIEW_EXECUTIVE_REPORTS,
    Permission.VIEW_MATERIAL_REPORTS,
    Permission.REVIEW_MATERIAL_REQUESTS,
    Permission.CLOSE_MATERIAL_CUSTODY,
  ],
  [Roles.PROJECT_MANAGER]: [
    Permission.MANAGE_PROJECTS,
    Permission.APPROVE_PROJECTS,
    Permission.MANAGE_TASKS,
    Permission.APPROVE_TASKS,
    Permission.VIEW_ANALYTICS,
    Permission.VIEW_EXECUTIVE_REPORTS,
    Permission.CREATE_MATERIAL_REQUESTS,
    Permission.REVIEW_MATERIAL_REQUESTS,
    Permission.PREPARE_MATERIAL_REQUESTS,
    Permission.DISPATCH_MATERIAL_REQUESTS,
    Permission.RECONCILE_MATERIAL_CUSTODY,
    Permission.CLOSE_MATERIAL_CUSTODY,
    Permission.VIEW_MATERIAL_REPORTS,
  ],
  [Roles.ASSISTANT_PROJECT_MANAGER]: [
    Permission.MANAGE_PROJECTS,
    Permission.APPROVE_PROJECTS,
    Permission.MANAGE_TASKS,
    Permission.APPROVE_TASKS,
    Permission.VIEW_ANALYTICS,
    Permission.CREATE_MATERIAL_REQUESTS,
    Permission.REVIEW_MATERIAL_REQUESTS,
    Permission.PREPARE_MATERIAL_REQUESTS,
    Permission.DISPATCH_MATERIAL_REQUESTS,
    Permission.RECONCILE_MATERIAL_CUSTODY,
    Permission.VIEW_MATERIAL_REPORTS,
  ],
  [Roles.TEAM_LEAD]: [
    Permission.MANAGE_TASKS,
    Permission.APPROVE_TASKS,
    Permission.VIEW_ANALYTICS,
    Permission.CREATE_MATERIAL_REQUESTS,
    Permission.REVIEW_MATERIAL_REQUESTS,
    Permission.PREPARE_MATERIAL_REQUESTS,
    Permission.DISPATCH_MATERIAL_REQUESTS,
    Permission.RECONCILE_MATERIAL_CUSTODY,
  ],
  [Roles.TECHNICAL_STAFF]: [
    Permission.CREATE_MATERIAL_REQUESTS,
    Permission.RECONCILE_MATERIAL_CUSTODY,
  ],
};

export const BadgeCodes = {
  FIRST_APPROVAL: 'FIRST_APPROVAL',
  POINTS_500: 'POINTS_500',
  POINTS_1000: 'POINTS_1000',
  MONTHLY_TOP_3: 'MONTHLY_TOP_3',
};

